# Site settings
title: БалалAI/ka - обучение без учителей AI 
email: balalaika.main@gmail.com
description: >-
   Надгосударственное, аполитичное и совместно изменяемое web-пространство для самоорганизации.
url: "https://balal.ai" #
baseurl: "/ka" # The subpath of your site

## => Theme
##############################
theme: jekyll-text-theme 
text_skin: dark # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"

source: src
destination: ./_site # Standard local build output, GitHub Pages ignores this for serving

# Below config is overwritten with _includes/head/custom.html , feel free to remove it
# Request access from balalaika.main@gmail.com to https://analytics.google.com/analytics/web/provision/?pli=1#/p487036726/
analytics:
  google:
    tracking_id: "G-QJZ72VPCP4" 

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Use GitHub Flavored Markdown
  hard_wrap: false

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: balal-ai-ka/balal-ai-ka.github.io
repository_tree: main/src

## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)

## TOC
toc:
  selectors: "h1,h2,h3"

## => Paginate v2
##############################
pagination: # using jekyll-paginate-v2 as dependency of jekyll-auto-authors
  enabled: true
  per_page: 9
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true

## => Autopages
##############################
autopages:

  # Other autopage configs stay the same
  enabled: true

  categories:
    enabled: false
  tags:
    enabled: false
  collections:
    enabled: false

  # This block is from jekyll-auto-authors plugin
  authors:
    enabled: true
    data: '_data/authors.yml'
    # Uncomment the line below to force exclude certain author usernames from autopage generation.
    # exclude: [ "author1", "author2" ]
    layouts: 
      - 'author.html' # We'll define this layout in the next step.
    title: 'Страница автора :author'
    permalink: '/author/:author/'
    slugify:
      mode: 'default' # choose from [raw, default, pretty, ascii or latin]
      cased: true # if true, the uppercase letters in slug will be converted to lowercase ones.

# Exclude from processing.

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
- scope:
    path: ""
    type: posts
  values:
    layout: article
    sharing: true
    license: true
    aside:
      toc: true
    show_edit_on_github: true
    show_subscribe: true
    pageview: true


## => Plugins
##############################
plugins:
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate-v2
  - jekyll-auto-authors  
