name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read # Read is enough for checkout
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync authors.yml from /src/_data to /_data/
        run: |
          rm -f ./_data/authors.yml
          cp ./_data/authors.yml ./_data/authors.yml
      - name: Setup Ruby
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0
      - name: Build with Jekyll (respecting config baseurl)
        # Build using baseurl: /ka from _config.yml
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Prepare Artifact for /ka deployment
        run: |
          mkdir ./deploy_root
          # Check if root index.html exists before copying
          if [ -f "./index.html" ]; then
            cp ./index.html ./deploy_root/index.html
          else
            echo "Root index.html not found, creating basic redirect."
            echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/ka/" /></head></html>' > ./deploy_root/index.html
          fi
          # Create /ka dir and move site contents into it
          mkdir ./deploy_root/ka
          # Use 'mv' carefully, ensure _site exists and has content
          if [ -d "./_site" ] && [ "$(ls -A ./_site)" ]; then
             mv ./_site/* ./deploy_root/ka/
          else
             echo "Warning: ./_site directory is empty or does not exist after build."
             # Optionally fail the build here: exit 1
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the custom structured directory
          path: './deploy_root'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # This URL might still point to root, user needs /ka
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4